import React, { useState } from 'react';
import { Info, X } from 'lucide-react';

const INFO = {
  dashboard: { impact: 'Centro de comando do teu negócio.', detail: 'Mostra em tempo real as marcações de hoje, receita do período, taxa de ocupação e clientes ativos. Todos os KPIs dependem de marcações com checkout concluído — sem checkout, a receita não conta.', links: 'Agenda (marcações), Financeiro (receita), Clientes (novos), Relatórios (tendências)' },
  agenda: { impact: 'A agenda é o coração operacional — erros aqui afetam receita e experiência do cliente.', detail: 'Cada slot confirmado reserva o profissional e o tempo. O checkout de cada marcação é o que regista receita, comissão e carimbo de fidelização. Marcações sem checkout ficam como "confirmadas" mas não geram valor financeiro.', links: 'Clientes (histórico), Financeiro (caixa), Fidelização (carimbos), Profissionais (disponibilidade)' },
  marcacoes: { impact: 'Lista completa de todas as marcações — útil para auditoria e reagendamentos em massa.', detail: 'Aqui vês todas as marcações independentemente do dia. Podes filtrar por estado, profissional ou data. Marcações canceladas não contam para receita nem para comissões.', links: 'Agenda (calendário), Clientes (perfil), Financeiro (comissões)' },
  listaEspera: { impact: 'Cada cliente na lista de espera é uma receita potencial que não queres perder.', detail: 'Quando surge um cancelamento de última hora, a lista de espera permite preencher o slot rapidamente. Clientes na lista que ficam sem resposta tendem a procurar a concorrência.', links: 'Agenda (slots livres), Clientes (contacto)' },
  encaixes: { impact: 'Slots de emergência que aumentam a ocupação sem alterar a agenda normal.', detail: 'Um encaixe é uma marcação fora do horário regular — útil quando há capacidade não utilizada. Contam como marcações normais para efeitos de receita e fidelização.', links: 'Agenda (disponibilidade), Profissionais (horários)' },
  bloqueios: { impact: 'Bloquear tempo protege os profissionais de marcações indesejadas.', detail: 'Férias, formações, reuniões — qualquer ausência deve ser bloqueada para evitar marcações automáticas pelo cliente nesse período. Bloqueios não geram receita nem comissões.', links: 'Agenda (disponibilidade), Profissionais (horários)' },
  clientes: { impact: 'A base de clientes é o ativo mais valioso da barbearia.', detail: 'Cada cliente tem histórico de visitas, total gasto e saldo de fidelização. Clientes com mais visitas geram mais receita e têm maior probabilidade de usar subscrições. O total gasto só inclui checkouts concluídos.', links: 'Agenda (marcações), Fidelização (carimbos), Financeiro (conta de cliente), Subscrições' },
  aniversarios: { impact: 'Um contacto no aniversário converte melhor do que qualquer promoção genérica.', detail: 'Clientes que recebem atenção no aniversário voltam mais e gastam mais. Usa esta lista para enviar um cupão ou mensagem personalizada. O impacto na fidelização é desproporcionalmente alto.', links: 'Clientes (perfil), Promoções (cupões), Fidelização' },
  profissionais: { impact: 'Os profissionais determinam a capacidade máxima da barbearia.', detail: 'Cada profissional ativo com horário definido cria slots disponíveis para marcação. A comissão configurada aqui é usada automaticamente no checkout de cada marcação.', links: 'Agenda (slots), Financeiro (comissões), Relatórios (desempenho)' },
  horariosPro: { impact: 'Sem horários definidos, os profissionais não aparecem disponíveis para marcação.', detail: 'O sistema gera slots automaticamente com base nos horários definidos aqui e nas horas de abertura do negócio. Alterações aos horários têm efeito imediato nas marcações futuras.', links: 'Agenda (slots disponíveis), Definições (horário do negócio)' },
  comissoesPro: { impact: 'A percentagem de comissão afeta diretamente o custo de cada serviço e a motivação da equipa.', detail: 'A comissão é guardada como snapshot no momento do checkout — se mudares a percentagem hoje, não afeta checkouts anteriores. Isto garante histórico financeiro estável.', links: 'Financeiro (comissões), Relatórios (profissionais), Agenda (checkout)' },
  desempenho: { impact: 'O desempenho dos profissionais mostra quem traz mais receita e quem precisa de apoio.', detail: 'Ranking por receita gerada, número de marcações e avaliações. Um profissional com alta receita mas baixa avaliação pode estar a gerar churn de clientes. Analisa sempre os dois em conjunto.', links: 'Relatórios (profissionais), Avaliações, Financeiro (comissões)' },
  servicos: { impact: 'O catálogo de serviços define o que podes vender e a quanto.', detail: 'Preço e duração ficam guardados como snapshot em cada marcação no momento em que é criada — podes alterar o preço sem afetar marcações já feitas. Serviços inativos não aparecem para marcação.', links: 'Agenda (marcações), Financeiro (receita), Relatórios (serviços)' },
  categorias: { impact: 'Categorias organizam o catálogo e facilitam análise por tipo de serviço.', detail: 'Relatórios de serviços agrupam receita por categoria — sem categorias bem definidas, perdes visibilidade sobre o que realmente está a gerar mais valor.', links: 'Serviços, Relatórios (serviços)' },
  produtos: { impact: 'Produtos vendidos no checkout aumentam o ticket médio por visita.', detail: 'Cada produto tem custo (o que pagas) e preço de venda (o que cobras). A margem é a diferença entre os dois. Stock baixo pode significar vendas perdidas no checkout.', links: 'Stock, Movimentos, Fornecedores, Comandas (checkout)' },
  stock: { impact: 'Stock abaixo do mínimo significa vendas perdidas e operação em risco.', detail: 'O sistema alerta quando um produto está abaixo do mínimo definido. Valor de stock = soma de (stock × custo) de todos os produtos — é um ativo que tens imobilizado.', links: 'Produtos, Movimentos, Fornecedores, Financeiro (despesas)' },
  movimentos: { impact: 'Histórico de entradas e saídas — essencial para detetar perdas e quebras.', detail: 'Cada ajuste de stock fica registado com data, quantidade e motivo. Se o stock baixa sem registo de venda, há uma quebra ou erro que precisa de investigação.', links: 'Stock, Fornecedores' },
  fornecedores: { impact: 'Fornecedores organizados significam encomendas mais rápidas quando o stock baixa.', detail: 'Mantém contactos e emails atualizados. Quando o stock de um produto baixa, consegues contactar o fornecedor certo diretamente a partir desta lista.', links: 'Stock, Produtos' },
  comandas: { impact: 'Comandas são o registo de tudo o que foi consumido numa visita antes de fechar a conta.', detail: 'Uma comanda aberta pode ter vários itens (serviços + produtos). Só fecha com pagamento — enquanto estiver aberta, não há receita registada. Comandas pendentes representam valor não cobrado.', links: 'Financeiro (caixa), Clientes (conta), Produtos (stock)' },
  caixa: { impact: 'A caixa regista tudo o que entra e sai fisicamente — base da contabilidade diária.', detail: 'Abre a caixa no início do dia com o fundo de maneio. Fecha no fim com a contagem real. A diferença entre o esperado e o contado é o que precisas de justificar. Sem caixa aberta, os movimentos ficam a descoberto.', links: 'Histórico, Entradas, Saídas, Financeiro (fluxo)' },
  historicoCaixa: { impact: 'Histórico de sessões de caixa — prova de que o dinheiro foi contado e fechado.', detail: 'Cada sessão fechada fica arquivada com valores de abertura, fecho e diferença. É a base para qualquer auditoria financeira. Sessões com diferença a vermelho precisam de justificação.', links: 'Caixa, Entradas, Saídas' },
  entradas: { impact: 'Entradas manuais que não vêm de marcações — gorjetas extra, reembolsos, outros.', detail: 'Qualquer dinheiro que entra no negócio fora do fluxo normal de marcações deve ser registado aqui para que o saldo de caixa seja correto.', links: 'Caixa, Fluxo de Caixa' },
  saidas: { impact: 'Saídas manuais — compras urgentes, despesas pequenas pagas a dinheiro.', detail: 'Registar todas as saídas é fundamental para o fecho de caixa bater certo. Saídas sem registo criam diferenças inexplicadas no final do dia.', links: 'Caixa, Despesas, Fluxo de Caixa' },
  receitas: { impact: 'Receitas recorrentes e não operacionais que complementam a receita de serviços.', detail: 'Inclui pagamentos de subscrições, vendas de produtos avulso, e outras entradas regulares. Ajuda a perceber a composição real da receita do negócio.', links: 'Financeiro (caixa), Subscrições, Relatórios (financeiro)' },
  despesas: { impact: 'Despesas controladas são a diferença entre lucro e prejuízo.', detail: 'Categoriza cada despesa (fornecedores, limpeza, marketing, outros). Sem categorização, é impossível perceber onde estás a gastar mais e onde podes cortar.', links: 'Saídas, Relatórios (financeiro), Fluxo de Caixa' },
  comissoesFinanceiro: { impact: 'Comissões devidas aos profissionais — um custo que reduz a margem por serviço.', detail: 'As comissões são calculadas automaticamente no checkout com base na percentagem configurada por profissional. Este ecrã mostra o que está acumulado e o que já foi pago.', links: 'Profissionais (comissões), Agenda (checkout), Relatórios (profissionais)' },
  contaCliente: { impact: 'Saldo positivo do cliente funciona como pré-pagamento — reduz cancelamentos de última hora.', detail: 'Um cliente com saldo na conta tem muito menos probabilidade de não aparecer. Podes carregar a conta com vouchers, reembolsos ou pagamentos antecipados.', links: 'Clientes (perfil), Comandas (checkout)' },
  contaProfissional: { impact: 'Saldo de adiantamentos e deduções dos profissionais — controlo de pagamentos internos.', detail: 'Útil quando pagas comissões parcialmente antecipadas ou tens deduções acordadas. O histórico fica registado por profissional.', links: 'Profissionais, Financeiro (comissões)' },
  fluxoCaixa: { impact: 'O fluxo de caixa é o único número que te diz se o negócio está saudável.', detail: 'Mostra entradas vs saídas por período — se as saídas forem consistentemente maiores que as entradas, há um problema de sustentabilidade mesmo que a receita pareça boa.', links: 'Caixa, Entradas, Saídas, Despesas, Receitas' },
  relatorios: { impact: 'Relatórios transformam dados em decisões — sem eles, geris às cegas.', detail: 'Cada relatório cruza dados de múltiplos módulos. A qualidade dos dados depende de checkouts concluídos, despesas registadas e clientes cadastrados corretamente.', links: 'Todos os módulos contribuem para os relatórios' },
  relatorioMarcacoes: { impact: 'Taxa de ocupação e padrões de marcação — onde estás a perder slots.', detail: 'Identifica os dias e horas com mais e menos procura. Uma taxa de ocupação abaixo de 60% indica que há capacidade desperdiçada. Acima de 90% pode significar que precisas de mais profissionais.', links: 'Agenda, Profissionais, Clientes' },
  relatorioClientes: { impact: 'Frequência, retenção e valor de vida por cliente.', detail: 'Clientes com alta frequência e alto gasto são os mais valiosos. Identifica clientes que não voltam há mais de 60 dias — são candidatos a uma campanha de reativação.', links: 'Clientes, Fidelização, Promoções' },
  relatorioProfissionais: { impact: 'Receita e produtividade por profissional — base para ajustar comissões e horários.', detail: 'Um profissional com pouca receita pode precisar de mais promoção ou formação. Compara sempre receita com avaliações — alta receita com baixa avaliação é um sinal de alerta.', links: 'Profissionais, Agenda, Financeiro' },
  relatorioFinanceiro: { impact: 'Visão consolidada de receita, despesas e margem — o relatório mais importante.', detail: 'Cruza receita de serviços, vendas de produtos, despesas e comissões para mostrar a margem real. Usa este relatório antes de tomar qualquer decisão sobre preços ou contratações.', links: 'Financeiro (todos os submódulos), Agenda' },
  relatorioServicos: { impact: 'Quais serviços vendem mais e quais são mais rentáveis — não é a mesma coisa.', detail: 'Um serviço barato e rápido pode ser mais rentável por hora do que um serviço caro e lento. Analisa receita por hora de serviço, não só preço total.', links: 'Serviços, Agenda, Financeiro' },
  relatorioProdutos: { impact: 'Rotação de stock e margem por produto — mostra o que realmente vale ter em loja.', detail: 'Produtos com alta margem e alta rotação são os mais valiosos. Produtos com baixa rotação imobilizam capital. Considera retirar produtos que não vendem há 60+ dias.', links: 'Produtos, Stock, Movimentos' },
  relatorioFidelizacao: { impact: 'Eficácia do programa de carimbos — está a trazer clientes de volta?', detail: 'Se poucos clientes estão a atingir a recompensa, o threshold pode ser demasiado alto. Um programa de fidelização só funciona se os clientes sentirem que a recompensa é alcançável.', links: 'Fidelização, Clientes, Agenda' },
  relatorioSubscricoes: { impact: 'Receita recorrente de subscrições — o rendimento mais previsível do negócio.', detail: 'Subscrições ativas geram receita garantida independentemente do número de visitas. Acompanha a taxa de churn (subscritores que cancelam) — acima de 10% por mês é preocupante.', links: 'Subscrições, Clientes, Financeiro' },
  fidelizacaoPrograma: { impact: 'O programa de carimbos é o mecanismo de retenção mais eficaz para uma barbearia.', detail: 'Clientes com programa de fidelização voltam em média 40% mais vezes. O threshold (número de carimbos para recompensa) deve ser alcançável em 2-3 meses com visita normal. Demasiado alto e os clientes desistem.', links: 'Clientes (carimbos), Agenda (checkout), Relatórios (fidelização)' },
  fidelizacaoPontos: { impact: 'Saldo de carimbos por cliente — quem está perto da recompensa.', detail: 'Clientes com 8-9 carimbos estão a uma visita da recompensa — são candidatos ideais a um lembrete. Intervir neste momento aumenta muito a probabilidade de regresso.', links: 'Clientes, Agenda (checkout), Fidelização (programa)' },
  fidelizacaoRecompensas: { impact: 'As recompensas são o que motiva o cliente a voltar — têm de parecer valiosas.', detail: 'Uma recompensa percebida como pouco atrativa não muda comportamento. O corte grátis funciona bem. Considera adicionar recompensas intermédias (desconto no 5.º corte) para manter motivação.', links: 'Fidelização (programa), Clientes, Promoções' },
  subscricoes: { impact: 'Subscrições criam receita previsível e reduzem a dependência de marcações avulsas.', detail: 'Um cliente com subscrição ativa visita mais vezes e churn menos. A chave é garantir que o valor da subscrição é claramente superior ao valor de marcações individuais.', links: 'Clientes, Financeiro (receitas), Relatórios (subscrições)' },
  promocoes: { impact: 'Promoções bem direcionadas aumentam receita nos períodos mais fracos.', detail: 'Evita promoções genéricas — direciona descontos para clientes que não voltam há 30+ dias ou para slots com baixa ocupação. Promoções mal direcionadas reduzem margem sem aumentar volume.', links: 'Clientes, Agenda (ocupação), Relatórios' },
  cupoes: { impact: 'Cupões são promoções com código — rastreáveis e controláveis.', detail: 'Ao contrário de descontos automáticos, cupões precisam de ser ativados — isso dá-te controlo sobre quem beneficia e quando. Monitoriza a taxa de uso de cada cupão.', links: 'Promoções, Clientes, Comandas (checkout)' },
  definicoesNegocio: { impact: 'Os dados do negócio aparecem para o cliente — erros aqui afetam a perceção de profissionalismo.', detail: 'Nome, morada, telefone e horários são os dados base que o cliente vê ao fazer marcação. Mantém sempre atualizados — horários errados geram marcações fora de horas.', links: 'Agenda (slots gerados pelos horários), App do cliente' },
  definicoesAgenda: { impact: 'A configuração da agenda define as regras do jogo para todas as marcações.', detail: 'O slot mínimo determina a granularidade da agenda. Antecedência mínima evita marcações de última hora impossíveis de gerir. Lista de espera e encaixes devem estar ativos se queres maximizar ocupação.', links: 'Agenda, Profissionais (horários)' },
  definicoesUtilizadores: { impact: 'Utilizadores com permissões erradas são um risco de segurança e operacional.', detail: 'Cada colaborador deve ter acesso apenas ao que precisa. Um barbeiro não precisa de ver relatórios financeiros. Revê as permissões regularmente, especialmente após saídas de pessoal.', links: 'Todas as páginas (controlo de acesso)' }
};

export default function PageInfo({ page }) {
  const [open, setOpen] = useState(true);
  const d = INFO[page];
  if (!d || !open) return null;
  return (
    <div style={{ background: 'rgba(201,168,39,0.08)', border: '1px solid rgba(201,168,39,0.25)', borderRadius: 10, padding: '14px 18px', marginBottom: 20, display: 'flex', gap: 12, alignItems: 'flex-start' }}>
      <Info size={16} style={{ color: '#C9A227', flexShrink: 0, marginTop: 2 }} />
      <div style={{ flex: 1 }}>
        <div style={{ fontWeight: 600, fontSize: 13, color: '#C9A227', marginBottom: 4 }}>{d.impact}</div>
        <div style={{ fontSize: 12, color: 'var(--text-sec)', lineHeight: 1.6 }}>{d.detail}</div>
        {d.links && <div style={{ fontSize: 11, color: 'var(--text-sec)', marginTop: 6 }}><span style={{ color: '#C9A227' }}>Ligado a: </span>{d.links}</div>}
      </div>
      <button onClick={() => setOpen(false)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-sec)', padding: 0, flexShrink: 0 }} aria-label="Fechar informação"><X size={14} /></button>
    </div>
  );
}
